apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort:  {{  if .Values.service.targetPort .Values.service.targetPort .Values.service.port }}

  selector:
    app: techtrends
  type: {{ .Values.service.type }} 
