namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: rolak/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 3111

probes:
  livenessProbe:
    httpGet:
      path: /healthz
      port: 3111
  readinessProbe:
      httpGet:
      path: /healthz
      port: 3111
